### ISSUE TITLE
Scanner does not work.

### ISSUE THREAD

**Issue by ghost** [ScriptSK/Reaper-Software-Suite#3]
Installed DotNet DevPack 4.7.2 matching the version in "PS4 Reaper Studio.exe.config"

I do not understand why the scanner is failing.

```************** Exception Text **************
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.ReadString()
   at _rUQBohV1KrOF3H8BWUNVyPvlsYr._26E8Jw1S8dSPl5KrDcX4BlljFkF(Byte[] , UInt64 )
   at _MxuHsJLMgMvIzApO33X9bDbLVnN._Cpi1zemP6J7mtZ9u068Nex2eshe()
   at _MxuHsJLMgMvIzApO33X9bDbLVnN._PBpN2BbBgyqBco1cUpjnDsETemdA(Boolean )
   at _3Sa4KAhRcFw3cCxBp2AByV4calt._A7x8JYi7HawAj3R9wZmlKtRXHRJ()
   at _PG8YPkgDNicFPNCb5qwKbOL3Bhg._ioejrrQDfF8dz2ibmietWiDbYgk()
   at _PG8YPkgDNicFPNCb5qwKbOL3Bhg._iKP1rshDQig141v75jZBQGxMg5E(Object , EventArgs )
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at DevExpress.XtraEditors.BaseButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.Utils.Controls.ControlBase.BaseWndProc(Message& m)
   at DevExpress.XtraEditors.BaseControl.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   ```
   
   Sorry if this is stupidly simple, I am new to windows and use it exclusively for Homebrew purposes.

**Comment by Tom-NeverNull** [comment]
Updated to  V01.0.2.28745 (Beta3.2)
Now I don't get that error, but the Scanner simply does nothing now... No error, no output

**Comment by Pharaoh2k** [comment]
Yes, the scanner has never worked, it was just a placeholder. Maybe in a future version it will get added.
Use PS4 Cheater, PS Cheater Neo and/or Cheat Engine for scanning the memory.
